name: Build and Push to ECR
on:
  push:
    branches: ['main','dev']

jobs:
  build-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Trivy Scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'fs'
          severity: HIGH,CRITICAL
          exit-code: '0'

      - name: Build Docker image
        run: docker build -t 977098999802.dkr.ecr.us-east-1.amazonaws.com/petclinic-dev-repo:latest .

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: 977098999802.dkr.ecr.us-east-1.amazonaws.com/petclinic-dev-repo:latest
          format: table
          exit-code: '0'
          ignore-unfixed: true
          severity: CRITICAL,HIGH

      - name: Push image to ECR
        run: echo "push"
              